env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - prettier
globals:
  mockDB: false
  describe: false
  it: false
  expect: false
  beforeEach: false
  afterEach: false

parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  "project": "./tsconfig.json"
  "tsconfigRootDir": "./"
plugins:
  - "@typescript-eslint"
  - import
rules:
  # enable to omit `.ts` for alias
  import/extensions: off
  import/prefer-default-export: off
  import/no-default-export: error
  class-methods-use-this: off
  import/no-extraneous-dependencies: [off, { "devDependencies": ["**/*.test.ts"] }]
  no-unused-vars: off
  "@typescript-eslint/no-unused-vars": ["error"]
  no-useless-constructor: off
  no-empty-function: [error, { allow: ["constructors"] }]
settings:
  "import/resolver":
    typescript:
